INSERT INTO usertypes (id, usertype_desc)
VALUES (1, 'Admin'),
(2, 'Guest');

INSERT INTO users (email, password, usertype_id)
VALUES ('admin1@gmail.com', 'admin1', 1);


INSERT INTO products (name, price, quantity, thumbnail_photo_url, description, category, number_of_ratings, avg_rating)
VALUES ('Nanoleaf light-up wall panels', 199.99, 20, 'https://pisces.bbystatic.com/image2/BestBuy_US/images/products/6039/6039500_sd.jpg', 'Modular LED light panels designed to add a stunning statement of artistic technology to your space.', 'Lifestyle', 500, 4.2),
('OMZIN Women Lapel Wrap Coat Outwear Long Overcoat Plue Size Jacket', 59.99, 100, 'https://m.media-amazon.com/images/I/61OckGLlZUL._AC_UL320_.jpg', 'Long trench coat with belt, double breasted storm flap button closure help to keep wind out. Thigh-length and detachable belt gives you a touch of versatility to handle ever-changing weather. 2 hand pockets lend a warm place for chilly hands on cold mornings.', 'Apparel', 20, 3.1),
('Jinlaili 30CM Christmas Door Wreath, Artificial Wreath Christmas Decoration, Front Door Hanging Xmas Wreath with Green Pine Twigs, Bowknot and Gold Double Clock Home Garland Ornament', 35.63, 35, 'https://m.media-amazon.com/images/I/91RUCrHS3VL._AC_SL1500_.jpg', 'The christmas wreath is made of plastic so it is durable,non-toxic and harmless, no bad smell, not easy to be corroded or broken, you can keep it for long time.Bright colors for a pleasant atmosphere.
The door garland is about 30cm in diameter, Hang it above your fireplace, place it on your front door, windows, columns, or on a living room wall; This wreath will bring an enjoyable ambiance on Christmas Eve and Christmas Day.', 'Decorations', 3, 5),
('Christmas Doormat Indoor Outdoor Decor, Christmas Welcome Mat Door Mat Christmas Decorations Ornaments, Christmas Tree Mat for Home Front Door (23.6x35.4in,D)', 35.00, 100, 'https://m.media-amazon.com/images/I/A1ELnYlwCRL._AC_SL1500_.jpg', 'Perfect for Christmas Decor : Welcome guests to your home with this unique, seasonal Christmas Decorations Door Mat. Perfect for any deck, patio, porch, veranda and entryway and extend a warm welcome to all who enter your home.
Durable and Funny : The Christmas Door Mat is made of Crystal velvet super soft fabric, non-woven bottom, non-slip, washable, durable and not easy to damage. The front of the doormat is printed with interesting blessing embossing, which is suitable for festival theme and is placed at the indoor entrance to welcome guests.', 'Decorations', 80, 2.8),
('GEYUEMEY Welcome Sign, Welcome Sign Front Door Decor, 12 Inch Welcome Sign for Farmhouse Porch Front Porch Decorations Outdoor Hanging Farmhouse, Porch, Living Room, Housewarming Gifts, (Sunflower)', 16.00, 50, 'https://m.media-amazon.com/images/I/71nk2pHMpuL._AC_SL1500_.jpg', 'The Welcome Sign with thickened 3D effect in a classical script, vivid charming design is a friendly and hospitable way to make your house more of an approachable home and add a bold and inviting feeling to any wall or home so everyone will feel warmth and familiarity!
Unlike other door sign wreath with cheap eucalyptus and flimsy bow glued on, easy to drop. Made of sturdy Steel in warm and nice-looking color,our welcome sign for front porch brings a good texture for long-lasting use! Tired of flimsy sign,our Home Sweet Home Sign decor is worthy a try!', 'Decorations', 3000, 3.8),
('Muzagroo Art Pig with Glasses Oil Paintings for Living Room Wall Decor Modern Cool Canvas Wall Art for Bedroom Kids Room (24x24in)', 28.00, 30, 'https://m.media-amazon.com/images/I/71+8J4gXNeL._AC_SL1100_.jpg', 'Lovely pig with glasses,adorkable expression makes you smile every time you see it.
100% hand painted oil painting, with raised texture on canvas, high quality canvas and environmental oil paints material. Oil paints are waterproof and damp proof,paintings can be cleaned by wet cloth,avoid any possible oily stain. Size:24x24in(60x60cm)', 'Paintings', 104, 4.2),
('Unframed Inspirational Lettering Art Print,Quote&Saying Modern Art Print Set of 4 (8”X10” Canvas Painting，Motivational Phrases Wall Art Poster for Nursery or Kids Room Home Decor，No Frame', 25.00, 0, 'https://m.media-amazon.com/images/I/5150ftlKeFL._AC_SL1001_.jpg', 'With inspirational wall art picture to decorate your home is an amazing and affordable way. Combined unique, colorful letters also can instantly decorate your home and make your room atmosphere more interesting', 'Paintings', 233, 1.5),
('Everlands Art Flower Art Print Canvas Painting Contemporary Wall Picture Home Decoration for Bedroom Fashion Diamond Crystal Floral HD Giclee Artwork Stretched and Framed (40"x20", Crystal)', 59.00, 5, 'https://m.media-amazon.com/images/I/714lSs5xOqL._AC_SL1001_.jpg', 'Vibrant Flowers Canvas Print Wall Art Giclee Artwork, HD pictures photo printed on canvas. Home decorations for living room, bedroom, office, bathroom, kitchen, hotel, bar etc.', 'Paintings', 40, 4.4),
('S01969 Wall Art HD Aurora Scenery Painting on Canvas Prints Stretched and Framed Pictures to Photo Ready to Hang for Home Decorations Office Wall Decor 24X36 inch', 72.00, 120, 'https://m.media-amazon.com/images/I/61-6ncHbD-L._AC_SL1200_.jpg', 'Wall Art Canvas prints 1 Panels Frame size:60x90cm x1pcs(24x36inchx1pcs)
High quality, HD prints on premium canvas, waterproof, UV resistant, fading resistant indoor. 
Wall Decorations Paintings for Living Room, Bedroom, Kitchen, Office, Hotel, Dining Room, Office, Bar etc.. Due to Different Brand of Monitors, Actual Wall Art Colors May be Slightly Different from the Product Image.', 'Paintings', 45, 1.2),
('Beauty Portrait Wall Art Abstract Knife Painting Canvas Pictures Lady Abstract Modern Artwork Contemporary Art Prints Framed for Home Office Kitchen Bathroom Bedroom Living Room Wall Decor 90 x 90cm', 35.63, 42, 'https://m.media-amazon.com/images/I/71PDWZE3rDL._AC_SL1150_.jpg', 'HD prints beauty portrait canvas art framed ready to hang.
Canvas art is vivid color, waterproof, UV resistant. High quality of the artwork makes feel of original nature and masterpiece.
A great gifts ideal for Valentines Day, Christmas, New Year, business gift and other purpose. Perfect home decoration choice for living room, bedroom, bathroom, kitchen, diningroom, office, hotel, bar wall decor and etc.', 'Paintings', 453, 2.3),
('5 Piece Wall Art Painting Mountain Lake On A Winter Evening Rock Ice Beach Snow Mountain Prints On Canvas The Picture Landscape Pictures Oil for Home Modern Decoration Print Decor for Living Room', 58.00, 15, 'https://m.media-amazon.com/images/I/61dqIujNNuL._AC_SL1000_.jpg', 'Size:10x16inchx2pcs, 8x20inchx2pcs, 8x24inchx1pcs, a total of 5 panels.
High Definition Modern Painting Artwork: We use modern advanced micro-spraying technology, highly restore the texture of the picture, rich colors, bring you visual enjoyment.', 'Paintings', 323, 2.9),
('Gold | Beautiful Moon phase hammered metal decor', 36.36, 32, 'https://m.media-amazon.com/images/I/71pE8C2uIdS._AC_SL1500_.jpg', 'Unique hammered metal moon phase garland, beautiful celestial piece.', 'Decorations', 32, 4.7),
('Macrame leaves wall hanging, macrame feather, macrame leaf, wall art, wall decor, macrame decor, housewarming gift, modern macrame, leaves', 29.52, 62, 'https://i.etsystatic.com/26369297/r/il/cb8259/2797747270/il_1140xN.2797747270_m5oi.jpg', '✨You can send this unique design dream catcher to yourself, your dearest family, friends, and everyone you loved. Blessing them have good dreams every night!', 'Decorations', 10, 3.5),
('Garden fairy string lights solar Firefly light landscape light 200 led', 20.00, 43, 'https://i.etsystatic.com/28051629/r/il/41a960/3272219415/il_794xN.3272219415_infm.jpg', '⭐️Wide Applications:Can be used indoors and outdoors, such as bedrooms, dormitories, bars, windows, wine glasses, Christmas trees, curtains, galleries, stairs, terraces, tents, backyards, porches, bookcases or pergola, they can add perfection to any space Atmosphere. firefly lights can also be used for various occasions, such as birthdays, weddings, holidays, Christmas, Halloween, lovers, parties, fashion shows and any place you want to decorate', 'Lightings', 30, 4.2),
('LED Window Curtain Lights- Warm White Energy Efficient Fairy Twinkle Lights- 300 Lights- Waterproof- Wedding Decor- Special Events', 33.52, 7, 'https://i.etsystatic.com/26369297/r/il/deaaa6/2790157824/il_794xN.2790157824_f9c3.jpg', '❤️These curtain lights go perfectly in any room and give just the right amount of illumination, ambience and glow to your space. The Curtain LED Lights are a Tapestry Girls EXCLUSIVE. Get the Curtain LED Lights today while they are still in stock!', 'Lightings', 43, 4.9),
('Tubicen LED Touch Night Light, 2000mAh Battery Table Lamp, LED Dimmable Bedsides Nightstand Lamp, Cordless LED Table Lamp, 4-Stage Dimming', 44.43, 10, 'https://i.etsystatic.com/22514112/r/il/200e47/2826707459/il_794xN.2826707459_83pp.jpg', 'Tubicen Jingle Series night light fixture is made of excellent quality LED and professional optical configuration, providing 2400K light perfectly to allow for a comfortable lighting experience.', 'Lightings', 80, 3.7),
('Cute LED Night Light Silicone Touch Sensor Cat Night Lamp', 29.99, 25, 'https://i.etsystatic.com/32141424/r/il/a29bf2/3444882275/il_794xN.3444882275_5csz.jpg', 'Desktop Decor | Night Lamp | Description of power switch: Press the power switch on the bottom of the product to turn on the light (the color is warm yellow); press the power switch again to turn off the light. ', 'Lightings', 38, 4.9),
('Cute Duck Night Light | Cute Duck Silicone LED Light | Cute Duck Silicone LED Night Light | Cute Animal Night Light', 37.81, 14, 'https://i.etsystatic.com/29070435/r/il/08f0af/3250787582/il_794xN.3250787582_mif0.jpg', 'ADORABLE DUCK: This adorable duck lamp can take your mind off any problems when you see it.', 'Lightings', 77, 1.3),
('Dried Flower Wreath, Gold hoop wreath, white, indoor wreath, boho wall decor accent, Pampas Grass, bleached ruscus, dried flowers, hygge', 10.95, 23, 'https://i.etsystatic.com/9992882/r/il/861cc6/2784804701/il_794xN.2784804701_am4c.jpg', 'A beautiful white and ivory wreath arranged on a gold hoop made with soft and fluffy dried pampas grass, white dried Italian ruscus, thistle and other dried flowers. This would be a gorgeous soft wall accent in a bedroom, kids room, sunroom, livingroom, entryway or anywhere you like to relax indoors!', 'Decorations', 32, 4.2);

INSERT INTO reviews (product_id, username, comment, rating)
VALUES (2, 'Harry Potter', 'Great Product', 4), (1, 'Hermione Granger', 'Loved using it', 4.5), (2, 'Rachel Greene','Superb jacket... I just loved its color and also its super comfy...', 4.5), (1, 'Ronald Weasley','Looks great', 4.2), (3, 'Mike Ross','Not so good..It doesnot look great as in the picture', 2), (3, 'Harvey Spector','It is good but not worth the price', 3.2), (5, 'Donna Cooper','Too small in size', 3.4), (2, 'Jon Snow','Material is not so good', 2.1), (2, 'Robb Stark','Nice fit', 4), (4, 'Arya Stark', 'Loved the doormat', 4.9), (2, 'Michael Scott','Gives me the perfect winter look', 4.6), (3, 'Raj Sharma','Good product', 2.3), (5, 'John Doe','Super great pattern', 4.2);

